FROM node:20-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN chmod +x node_modules/.bin/next
RUN npm run build

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
# FROM node:20-alpine AS base

# WORKDIR /app

# # Install dependencies only when needed
# COPY package.json package-lock.json ./
# RUN npm ci

# # Copy all files and build
# COPY . .
# RUN npm run build

# ENV NODE_ENV=production
# ENV NEXT_TELEMETRY_DISABLED=1

# EXPOSE 3000

# CMD ["npm", "start"]
