services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      restart: always
      ports:
        - "5000:5000"

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      command: npm start
      restart: always
      environment:
        - BACKEND_URL=http://backend:5000
      ports:
        - "3000:3000"

  chainlit:
      build:
        context: ./chainlit_app
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8000:8000"
  
  relational_db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_volume: